### ISSUE TITLE
Cannot use Bootstrapper in a tokio task.

### ISSUE THREAD

**Issue by conorbros** [mitsuhiko/tokio-unix-ipc#2] opened 2021-09-20 08:36 UTC
If I try to do the code snippet below, to have a background task wait for a message over IPC I get a compiler error:
```rust
`Cell<isize>` cannot be shared between threads safely
```

Is there any reason the `sender` field of `Bootstrapper` can't be changed from a `RefCell` to an `Arc` which would make this possible? Or is there a different way to go about what I am trying to achieve?

```rust   
tokio::spawn(async move {
        let bootstrapper = {
            let bootstrapper = tokio_unix_ipc::Bootstrapper::bind("/tmp/test-uds").unwrap();
            bootstrapper.send(Message::Sender(tx)).await.unwrap();
            bootstrapper
        };

        tokio::select! {
            res = rx.recv() => {
                if let Ok(msg) = res {
                    match msg {
                        _ => {}
                    }
                }
            }
        };
});
```

**Comment by conorbros** [comment] 2021-09-20 08:55
Example in this repo: https://github.com/conorbros/tokio-unix-ipc

**Comment by mitsuhiko** [comment] 2022-11-01 12:42
Duplicate of #13

**Closed by mitsuhiko** 2022-11-01 12:42 UTC
